<a href="https://colab.research.google.com/github/aryan-at-ul/tf_learning/blob/main/tensors_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.8.0


In [3]:
#constants in tensoflow, not very usefull  , unmutable in nature 
scalar = tf.constant(7)
print(scalar) # note the shape is empty !! 0 order tensor 
# https://www.tensorflow.org/api_docs/python/tf/constant
print(scalar.ndim)

vector = tf.constant([10,11])
print(vector)
print(vector.ndim)


matrix = tf.constant([[10,11],[12,13]])
print(matrix)
print(matrix.ndim)


matrix2 = tf.constant([[10.,11.],[12.,13.]],dtype = "float16")
print(matrix2)
print(matrix2.ndim)


tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[1,2,3],
                      [4,5,6]],
                      [[1,2,3],
                       [1,2,3],
                       ]
                      ])

print(tensor)
print(tensor.ndim)

tf.Tensor(7, shape=(), dtype=int32)
0
tf.Tensor([10 11], shape=(2,), dtype=int32)
1
tf.Tensor(
[[10 11]
 [12 13]], shape=(2, 2), dtype=int32)
2
tf.Tensor(
[[10. 11.]
 [12. 13.]], shape=(2, 2), dtype=float16)
2
tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [1 2 3]]], shape=(3, 2, 3), dtype=int32)
3


In [4]:
# tensor using variables  https://www.tensorflow.org/api_docs/python/tf/Variable
#mutable tensor 

t1 = tf.Variable([10,7])
# t2 = tf.Variable([12,12])
t1[0].assign(7) # this is how you change elements in a tensor

t1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [5]:
# creating random tensors, for weights and stuff etc
# https://www.tensorflow.org/api_docs/python/tf/random/uniform  or normal or maybe someother 

t1 = tf.random.Generator.from_seed(42) # check all possible stuff in Generator. fx
t1 = t1.normal(shape = (3,3))
print(t1)
print(t1.ndim)

t2 = tf.random.Generator.from_seed(42) 
t2 = t2.normal(shape = (3,3))

t1, t2, t1 == t2  # this guy is true because we used that seed 42 while creating both tensors


tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193765 -1.8107855 ]
 [ 0.09988727 -0.50998646 -0.7535806 ]], shape=(3, 3), dtype=float32)
2


(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193765, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535806 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193765, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535806 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [6]:
# shuffling the orders in tensors // part of manipulating the tensors !!! 
# shuffling comes handy when trying to think in terms of training data set, should be nice variation there so that network learns variety overt the data set 
#now listen to party anthem : Everyday I'm shuffling ,Shuffling, shuffling
# https://www.tensorflow.org/api_docs/python/tf/random/shuffle
print(t2)

t3 = tf.random.shuffle(t2,seed = 42) # this way seed wont make a difference ok !!!  this is operation level seed, this used for randominzing

print(t3)

# tf.random.set_seed(42) # global level seed  IMPORTANT

t3 = tf.random.shuffle(t2,seed = 42)

print(t3)


tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193765 -1.8107855 ]
 [ 0.09988727 -0.50998646 -0.7535806 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.09988727 -0.50998646 -0.7535806 ]
 [-1.2573844  -0.23193765 -1.8107855 ]
 [-0.7565803  -0.06854702  0.07595026]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.09988727 -0.50998646 -0.7535806 ]
 [-1.2573844  -0.23193765 -1.8107855 ]
 [-0.7565803  -0.06854702  0.07595026]], shape=(3, 3), dtype=float32)


In [7]:
# creating tensors from numpy , very very important, jesus said that !!!
import numpy as np
t0 = tf.zeros([3,3])
t1 = tf.ones([3,3])
print(t0)
print(t1)

#converting numopy arrays into tensors 

na = np.arange(1,25,dtype = np.int32)
print("numpy array:",na)
tna = tf.constant(na)
print("tensor from numpy",tna)

tna = tf.constant(na, shape = (2,3,4))
print(tna)

tna = tf.constant(na, shape = (3,1,8))
print(tna)

# batches , each batch  and x and y value this is one ex like to create training data
tna = tf.constant(na, shape = (3,4,2))
print(tna)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
numpy array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
tensor from numpy tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[[ 1  2  3  4  5  6  7  8]]

 [[ 9 10 11 12 13 14 15 16]]

 [[17 18 19 20 21 22 23 24]]], shape=(3, 1, 8), dtype=int32)
tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]], shape=(3, 4, 2), dtype=int32)


In [8]:
# getting attribute information from a tensor 
# shape 
# rank (dimenstion)  this is not like rank of a matrix an all zero matrix will also have dim of 2, this is not matrix rank
# axis 
# size , all elements in there


tf4 = tf.zeros(shape = [2,3,4,5])
print(tf4)

print(tf4.shape)

print(tf4.ndim)

print(tf.size(tf4))


print(tf4.dtype)


print(tf4.shape[0]) # elements along 0 axis

print(tf4.shape[-1]) # elements in last axis that is  i = 3 here 

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)
(2, 3, 4, 5)
4
tf.Tensor(120, shape=(), dtype=int32)
<dtype: 'float32'>
2
5


In [9]:
# indexing tensors just like lists 

# get first 2 elements from each dimention 

print(tf4[:2,:2,:2,:2]) # slices 2 element in each dimention

# get first elemnt from each except the final one 

print(tf4[:1,:1,:1,:]) # to practice more this is important

tf.Tensor(
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]], shape=(2, 2, 2, 2), dtype=float32)
tf.Tensor([[[[0. 0. 0. 0. 0.]]]], shape=(1, 1, 1, 5), dtype=float32)


In [10]:
#changing and adding dim in an exisitng tensor 

tf2 = tf.zeros(shape = [2,2])
tf2 = tf.constant([[1,2],[3,4]])
print(tf2)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [11]:
print(tf2[:,-1]) # last elements last row elements

# this https://stackoverflow.com/a/64312636/4416197 answer explains additon at end or start
tf2_new = tf2[...,tf.newaxis] # this can be written as tf2[::::,tf.newaxis] but : should match nums of dimentions better to use 3 commas for all

print(tf2_new)


#alternale 
#https://www.tensorflow.org/api_docs/python/tf/expand_dims

tf2_new = tf.expand_dims(tf2,axis = 0) # extra dim added at begining 
print(tf2_new)

tf2_new = tf.expand_dims(tf2,axis = -1)
print(tf2_new)


tf2_new = tf.expand_dims(tf2,axis = 1)
print(tf2_new)

tf.Tensor([2 4], shape=(2,), dtype=int32)
tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]]], shape=(1, 2, 2), dtype=int32)
tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)
tf.Tensor(
[[[1 2]]

 [[3 4]]], shape=(2, 1, 2), dtype=int32)


In [12]:
# basic tensor operations 
# adding value to a tensor 

tfc = tf.constant([[10,7],[5,8]])

print(tfc + 10) # original is not changed

# some for other operators , /,*,- 

# can use built in libs for this

print(tf.multiply(tfc,10)) # libs are faster in execution time 
# print(tfc)

tf.Tensor(
[[20 17]
 [15 18]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  70]
 [ 50  80]], shape=(2, 2), dtype=int32)


In [13]:
# matrix multiplication, tuesday
#https://www.tensorflow.org/api_docs/python/tf/linalg/matmul

tf.matmul(tfc,tfc)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[135, 126],
       [ 90,  99]], dtype=int32)>

In [14]:
tf1 = tf.constant([[1,2,3],[3,4,5],[6,0,0]])
tf2 = tf.constant([[1,2],[0,0],[1,1]])

tf.matmul(tf1,tf2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  5],
       [ 8, 11],
       [ 6, 12]], dtype=int32)>

In [15]:
#change datatype of tensor 

tf1 = tf.zeros(shape= [2,3])
print(tf1)

tf2 = tf.cast(tf1,dtype = tf.float16)
print(tf2)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float16)


In [16]:
# tensor finding min and max in a tensor , aggregation

#get the absolute values , useless 

t = tf.constant([[-3.,-10.]])
print(tf.abs(t))

# get min max mean ans sum
print(tf.reduce_min(t))
print(tf.reduce_max(t))
print(tf.reduce_mean(t))
print(tf.reduce_sum(t))

#there is tfp if dtype is not converned else tf.math.reduce_variance for std

tf.Tensor([[ 3. 10.]], shape=(1, 2), dtype=float32)
tf.Tensor(-10.0, shape=(), dtype=float32)
tf.Tensor(-3.0, shape=(), dtype=float32)
tf.Tensor(-6.5, shape=(), dtype=float32)
tf.Tensor(-13.0, shape=(), dtype=float32)


In [17]:
#find positional min max of a tensor

t = tf.random.uniform(shape = [50])
print(t)

# index of max element , used in getting claasified class after softmx

print(tf.argmax(t))

#index on our larget value 

print(t[tf.argmax(t)])

print(tf.reduce_max(t))

#similar for argmin 


tf.Tensor(
[0.20180166 0.02993655 0.29874313 0.05900979 0.5658611  0.95510876
 0.741681   0.80384326 0.24423528 0.48716223 0.4281559  0.01976371
 0.66755164 0.6426437  0.84699893 0.4989885  0.20904541 0.22064817
 0.62735474 0.8279309  0.79675996 0.13413322 0.17015791 0.34593034
 0.8060794  0.9169941  0.96743405 0.91735625 0.14375842 0.81203616
 0.6019386  0.5719905  0.2493993  0.7753123  0.8230903  0.03962934
 0.08865273 0.8446951  0.80418336 0.22604156 0.96647835 0.694126
 0.6496471  0.3185451  0.85347927 0.07468915 0.23809493 0.6519022
 0.27941263 0.25375998], shape=(50,), dtype=float32)
tf.Tensor(26, shape=(), dtype=int64)
tf.Tensor(0.96743405, shape=(), dtype=float32)
tf.Tensor(0.96743405, shape=(), dtype=float32)


In [18]:
#squeezing a tensor , removing all single dimention 

t = tf.constant(tf.random.uniform(shape=[50]),shape = (1,1,1,1,50))
print(t)

tf.Tensor(
[[[[[0.41150475 0.3257829  0.7080709  0.11352336 0.32682812 0.30486846
     0.23868585 0.2636211  0.5658953  0.36017644 0.75039196 0.03576338
     0.1492691  0.12522829 0.67341423 0.05706739 0.29139876 0.22187865
     0.8204479  0.23373115 0.35571718 0.09945822 0.24636054 0.9221815
     0.15445518 0.16265392 0.6043472  0.14161384 0.70709455 0.5286578
     0.6555886  0.00974333 0.8676162  0.23223698 0.01577353 0.83913255
     0.6483557  0.81520677 0.9677216  0.08437061 0.71206796 0.21761584
     0.30135286 0.5154525  0.43339407 0.9390893  0.28302848 0.6430999
     0.31236076 0.99156487]]]]], shape=(1, 1, 1, 1, 50), dtype=float32)


In [19]:
t_sq = tf.squeeze(t)
print(t_sq) # this operation is very important 

tf.Tensor(
[0.41150475 0.3257829  0.7080709  0.11352336 0.32682812 0.30486846
 0.23868585 0.2636211  0.5658953  0.36017644 0.75039196 0.03576338
 0.1492691  0.12522829 0.67341423 0.05706739 0.29139876 0.22187865
 0.8204479  0.23373115 0.35571718 0.09945822 0.24636054 0.9221815
 0.15445518 0.16265392 0.6043472  0.14161384 0.70709455 0.5286578
 0.6555886  0.00974333 0.8676162  0.23223698 0.01577353 0.83913255
 0.6483557  0.81520677 0.9677216  0.08437061 0.71206796 0.21761584
 0.30135286 0.5154525  0.43339407 0.9390893  0.28302848 0.6430999
 0.31236076 0.99156487], shape=(50,), dtype=float32)


In [20]:
# one hot encoding , very important , this one is hot 

alist = [0,1,2,3,4,3] # one hot encode this list of indexed 

ahotlist = tf.one_hot(alist, depth = 4)

print(ahotlist)

# we can have custom value for one hot encoding 


print(tf.one_hot(alist,depth = 4, on_value = "on", off_value = "off")) # this is useless but helpful at the time of visualization etc 

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]], shape=(6, 4), dtype=float32)
tf.Tensor(
[[b'on' b'off' b'off' b'off']
 [b'off' b'on' b'off' b'off']
 [b'off' b'off' b'on' b'off']
 [b'off' b'off' b'off' b'on']
 [b'off' b'off' b'off' b'off']
 [b'off' b'off' b'off' b'on']], shape=(6, 4), dtype=string)


In [21]:
# some more maths operations on tensors 

#square 
print(tf.square(tf.squeeze(t)))
print(tf.sqrt(tf.squeeze(t)))
print(tf.math.log(tf.squeeze(t)))

# tensor created from numpy arrays are float64 type and from array they are float32 !!!!!!!!!!!

tf.Tensor(
[1.6933616e-01 1.0613450e-01 5.0136435e-01 1.2887554e-02 1.0681662e-01
 9.2944779e-02 5.6970932e-02 6.9496080e-02 3.2023752e-01 1.2972707e-01
 5.6308812e-01 1.2790195e-03 2.2281265e-02 1.5682124e-02 4.5348671e-01
 3.2566874e-03 8.4913239e-02 4.9230136e-02 6.7313480e-01 5.4630250e-02
 1.2653472e-01 9.8919375e-03 6.0693517e-02 8.5041869e-01 2.3856403e-02
 2.6456298e-02 3.6523557e-01 2.0054480e-02 4.9998271e-01 2.7947906e-01
 4.2979646e-01 9.4932533e-05 7.5275785e-01 5.3934015e-02 2.4880440e-04
 7.0414340e-01 4.2036515e-01 6.6456205e-01 9.3648505e-01 7.1184002e-03
 5.0704080e-01 4.7356654e-02 9.0813547e-02 2.6569128e-01 1.8783042e-01
 8.8188869e-01 8.0105126e-02 4.1357750e-01 9.7569250e-02 9.8320091e-01], shape=(50,), dtype=float32)
tf.Tensor(
[0.64148635 0.57077396 0.84146947 0.33693227 0.57168883 0.55214894
 0.48855484 0.51344043 0.75226015 0.600147   0.86625165 0.18911208
 0.38635358 0.35387608 0.8206182  0.23888783 0.53981364 0.47103995
 0.9057858  0.48345748 0.5964203  0.3

In [22]:
# gpu ? 

print(tf.config.list_physical_devices())

!nvidia-smi

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Tue Apr 19 15:12:29 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P0    27W /  70W |    266MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+--