<a href="https://colab.research.google.com/github/aryan-at-ul/tf_learning/blob/main/tensors_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.8.0


In [12]:
#constants in tensoflow, not very usefull  , unmutable in nature 
scalar = tf.constant(7)
print(scalar) # note the shape is empty !! 0 order tensor 
# https://www.tensorflow.org/api_docs/python/tf/constant
print(scalar.ndim)

vector = tf.constant([10,11])
print(vector)
print(vector.ndim)


matrix = tf.constant([[10,11],[12,13]])
print(matrix)
print(matrix.ndim)


matrix2 = tf.constant([[10.,11.],[12.,13.]],dtype = "float16")
print(matrix2)
print(matrix2.ndim)


tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[1,2,3],
                      [4,5,6]],
                      [[1,2,3],
                       [1,2,3],
                       ]
                      ])

print(tensor)
print(tensor.ndim)

tf.Tensor(7, shape=(), dtype=int32)
0
tf.Tensor([10 11], shape=(2,), dtype=int32)
1
tf.Tensor(
[[10 11]
 [12 13]], shape=(2, 2), dtype=int32)
2
tf.Tensor(
[[10. 11.]
 [12. 13.]], shape=(2, 2), dtype=float16)
2
tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [1 2 3]]], shape=(3, 2, 3), dtype=int32)
3


In [17]:
# tensor using variables  https://www.tensorflow.org/api_docs/python/tf/Variable
#mutable tensor 

t1 = tf.Variable([10,7])
# t2 = tf.Variable([12,12])
t1[0].assign(7) # this is how you change elements in a tensor

t1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [24]:
# creating random tensors, for weights and stuff etc
# https://www.tensorflow.org/api_docs/python/tf/random/uniform  or normal or maybe someother 

t1 = tf.random.Generator.from_seed(42) # check all possible stuff in Generator. fx
t1 = t1.normal(shape = (3,3))
print(t1)
print(t1.ndim)

t2 = tf.random.Generator.from_seed(42) 
t2 = t2.normal(shape = (3,3))

t1, t2, t1 == t2  # this guy is true because we used that seed 42 while creating both tensors


tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193763 -1.8107855 ]
 [ 0.09988727 -0.50998646 -0.7535805 ]], shape=(3, 3), dtype=float32)
2


(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [29]:
# shuffling the orders in tensors // part of manipulating the tensors !!! 
# shuffling comes handy when trying to think in terms of training data set, should be nice variation there so that network learns variety overt the data set 
#now listen to party anthem : Everyday I'm shuffling ,Shuffling, shuffling
# https://www.tensorflow.org/api_docs/python/tf/random/shuffle
print(t2)

t3 = tf.random.shuffle(t2,seed = 42) # this way seed wont make a difference ok !!!  this is operation level seed, this used for randominzing

print(t3)

# tf.random.set_seed(42) # global level seed  IMPORTANT

t3 = tf.random.shuffle(t2,seed = 42)

print(t3)


tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193763 -1.8107855 ]
 [ 0.09988727 -0.50998646 -0.7535805 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.09988727 -0.50998646 -0.7535805 ]
 [-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193763 -1.8107855 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.09988727 -0.50998646 -0.7535805 ]
 [-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193763 -1.8107855 ]], shape=(3, 3), dtype=float32)


In [39]:
# creating tensors from numpy , very very important, jesus said that !!!
import numpy as np
t0 = tf.zeros([3,3])
t1 = tf.ones([3,3])
print(t0)
print(t1)

#converting numopy arrays into tensors 

na = np.arange(1,25,dtype = np.int32)
print("numpy array:",na)
tna = tf.constant(na)
print("tensor from numpy",tna)

tna = tf.constant(na, shape = (2,3,4))
print(tna)

tna = tf.constant(na, shape = (3,1,8))
print(tna)

# batches , each batch  and x and y value this is one ex like to create training data
tna = tf.constant(na, shape = (3,4,2))
print(tna)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
numpy array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
tensor from numpy tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[[ 1  2  3  4  5  6  7  8]]

 [[ 9 10 11 12 13 14 15 16]]

 [[17 18 19 20 21 22 23 24]]], shape=(3, 1, 8), dtype=int32)
tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]], shape=(3, 4, 2), dtype=int32)


In [47]:
# getting attribute information from a tensor 
# shape 
# rank (dimenstion)  this is not like rank of a matrix an all zero matrix will also have dim of 2, this is not matrix rank
# axis 
# size , all elements in there


tf4 = tf.zeros(shape = [2,3,4,5])
print(tf4)

print(tf4.shape)

print(tf4.ndim)

print(tf.size(tf4))


print(tf4.dtype)


print(tf4.shape[0]) # elements along 0 axis

print(tf4.shape[-1]) # elements in last axis that is  i = 3 here 

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)
(2, 3, 4, 5)
4
tf.Tensor(120, shape=(), dtype=int32)
<dtype: 'float32'>
2
5


In [50]:
# indexing tensors just like lists 

# get first 2 elements from each dimention 

print(tf4[:2,:2,:2,:2]) # slices 2 element in each dimention

# get first elemnt from each except the final one 

print(tf4[:1,:1,:1,:]) # to practice more this is important

tf.Tensor(
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]], shape=(2, 2, 2, 2), dtype=float32)
tf.Tensor([[[[0. 0. 0. 0. 0.]]]], shape=(1, 1, 1, 5), dtype=float32)


In [54]:
#changing and adding dim in an exisitng tensor 

tf2 = tf.zeros(shape = [2,2])
tf2 = tf.constant([[1,2],[3,4]])
print(tf2)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [61]:
print(tf2[:,-1]) # last elements last row elements

# this https://stackoverflow.com/a/64312636/4416197 answer explains additon at end or start
tf2_new = tf2[...,tf.newaxis] # this can be written as tf2[::::,tf.newaxis] but : should match nums of dimentions better to use 3 commas for all

print(tf2_new)


#alternale 
#https://www.tensorflow.org/api_docs/python/tf/expand_dims

tf2_new = tf.expand_dims(tf2,axis = 0) # extra dim added at begining 
print(tf2_new)

tf2_new = tf.expand_dims(tf2,axis = -1)
print(tf2_new)


tf2_new = tf.expand_dims(tf2,axis = 1)
print(tf2_new)

tf.Tensor([2 4], shape=(2,), dtype=int32)
tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]]], shape=(1, 2, 2), dtype=int32)
tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)
tf.Tensor(
[[[1 2]]

 [[3 4]]], shape=(2, 1, 2), dtype=int32)


In [67]:
# basic tensor operations 
# adding value to a tensor 

tfc = tf.constant([[10,7],[5,8]])

print(tfc + 10) # original is not changed

# some for other operators , /,*,- 

# can use built in libs for this

print(tf.multiply(tfc,10)) # libs are faster in execution time 
# print(tfc)

tf.Tensor(
[[20 17]
 [15 18]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  70]
 [ 50  80]], shape=(2, 2), dtype=int32)


In [ ]:
# matrix multiplication, tuesday